language: python
python:
  - 3.7
  - 3.5
  - 2.7

jobs:
  include:
    - if: branch IN (master, develop)
      python: 3.8
    - if: branch IN (master, develop)
      python: 3.6
    - if: branch IN (master, develop)
      python: pypy
    - if: branch IN (master, develop)
      python: pypy3


install: pip install -U tox coveralls

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

cache: pip

# Coverall and Lint only in 3.7
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then tox -e lint; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ]; then coveralls; fi

deploy:
  - provider: pypi
    user: __token__
    password:
      secure: XBESZHLqZ1LpfhQS4ecdTlNRFwGZ4VbUnc2PvhdCW9uBy5ZAIFWqMM9qJY1ShPu1KSFiK+tQwcSIah6g5Rq5JJHXS8ZEvUGKjFWpDhTyRb+0Lfw3rniPeSUyA3YMNp7TlEhPYKUW/my93t0NixI30IoqcoZZIoA0BSqprbwvCmIZTCMmOfFNdoLIJ3071n9cxk4f6PvIM1mmUV0+pIFGnufiDruHlURFK0tmIvHENr3oXfettvgadXLdJw6UW1i+Ij/EZzRfsxJ51S3aTSM8+x+75gPzgFvgQl/uQhgangbY3RzMHdy0lz1nt3dqPkAcs9bxiKMXZvjJl19z6rcg8sAxCZ9idXhyNnCksWrER6ATcJGELPN5bozOgciwVe9F7HvszB3yBnJ93Sk5HNEHKk9GwaZ+gvf5olE7+PSIEnG9/Y+8z/PFTd1FwwKuR2UpzeQbeZDEtE3bb7m7h7Nl1QNNwjhLhZfWNVs1LnXLlUNpKFimOrFbBey3xcEIXTL/xsiIcunjJYT5afHbucEoh4b3/5Yn3RuiP2O+RA7SL34CGbC4pyAIdeDldutaklCvadyw+Elk2dVeHmFALnrx3dMovibbiWmL8iiXjGr2nOkz12KvUjzn+zI+oJ8sn9cshcKbN1gT0ZMFfeOUBewV/+TED9TJzLYZret68AhZG2o=
    server: https://test.pypi.org/legacy/
    skip_existing: true
    on:
      python: 3.7
      repo: rado0x54/python-carson-living
      branch: feature/setup-release-workflow
  - provider: pypi
    user: __token__
    password:
      secure: XBESZHLqZ1LpfhQS4ecdTlNRFwGZ4VbUnc2PvhdCW9uBy5ZAIFWqMM9qJY1ShPu1KSFiK+tQwcSIah6g5Rq5JJHXS8ZEvUGKjFWpDhTyRb+0Lfw3rniPeSUyA3YMNp7TlEhPYKUW/my93t0NixI30IoqcoZZIoA0BSqprbwvCmIZTCMmOfFNdoLIJ3071n9cxk4f6PvIM1mmUV0+pIFGnufiDruHlURFK0tmIvHENr3oXfettvgadXLdJw6UW1i+Ij/EZzRfsxJ51S3aTSM8+x+75gPzgFvgQl/uQhgangbY3RzMHdy0lz1nt3dqPkAcs9bxiKMXZvjJl19z6rcg8sAxCZ9idXhyNnCksWrER6ATcJGELPN5bozOgciwVe9F7HvszB3yBnJ93Sk5HNEHKk9GwaZ+gvf5olE7+PSIEnG9/Y+8z/PFTd1FwwKuR2UpzeQbeZDEtE3bb7m7h7Nl1QNNwjhLhZfWNVs1LnXLlUNpKFimOrFbBey3xcEIXTL/xsiIcunjJYT5afHbucEoh4b3/5Yn3RuiP2O+RA7SL34CGbC4pyAIdeDldutaklCvadyw+Elk2dVeHmFALnrx3dMovibbiWmL8iiXjGr2nOkz12KvUjzn+zI+oJ8sn9cshcKbN1gT0ZMFfeOUBewV/+TED9TJzLYZret68AhZG2o=
    skip_existing: true
    on:
      tags: true
      python: 3.7
      repo: rado0x54/python-carson-living
